---
- name: Setup Web Server
  hosts: all
  become: true

  tasks:
  - name: Install Apache2 & PHP Packages for Ubuntu Server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Set Time-Zone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Copy PHP Index File
    copy:
      src: ~/ansible/index.php
      dest: /var/www/html/index.php
      mode: 0644
