---
- name: Setup Web Server
  hosts: all
  become: true

  tasks:
  - name: Update Repository
    apt:
      update_cache: yes

  - name: Install Apache2 Package
    apt:
      name: apache2
      state: latest

  - name: Set Time-Zone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Copy PHP File
    copy:
      src: ~/ansible/index.php
      dest: /var/www/html/index.php
      mode: 0644
