---

- hosts: all
  become: true

  tasks:
  - name: Install Apache & PHP Packages for Ubuntu Server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Set Time-Zone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Copy PHP Index File for Site
    copy:
      src: ~/ansible/php_file/index.php
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: 0644
