---
- name: Setup Web Server
  hosts: all
  become: true

  tasks:
  - name: Install Apache2 Package
    apt:
      name: apache2
      state: present
  - name: Copy PHP file
    command: cp /home/vagrant/ansible/index.php /var/www/php/index.php
